In [40]:
from typing import List, Dict
import pandas as pd
from IPython.display import display, Markdown
import numpy as np
import csv

In [41]:
sample_data = {}
with open("tabela.csv", newline='', encoding='utf-8') as csvfile:
    csv_reader = csv.DictReader(csvfile)  # Create a DictReader object
    # Convert the CSV data to a list of dictionaries
    csv_data = [row for row in csv_reader]
    
    for row in csv_data:
        first_row = list(row.keys())[0]
        if not sample_data.__contains__(row[first_row]):
            values = list(row.values())
            values.pop(0)
            sample_data[row[first_row]] = values 
        # for key in row.keys():
        #     if sample_data.__contains__(key):
        #         sample_data[key].append(row[key])
        #     else:
        #         sample_data[key] = [row[key]]

    for item in sample_data.keys():
        print(f"{item} : {sample_data[item]}")  # Each item is a dictionary representing a row in the CSV
    # print(sample_data)


1 : ['161.4', '199.5', '215.7', '224.6', '230.2', '234.0', '236.8', '238.9', '240.5', '241.9', '243.0', '243.9', '244.7', '245.4', '245.9', '248.0', '251.1', '252.2', '253.3', '253.8']
2 : ['18.513', '19.000', '19.164', '19.247', '19.296', '19.329', '19.353', '19.371', '19.385', '19.396', '19.405', '19.412', '19.419', '19.424', '19.429', '19.446', '19.471', '19.479', '19.487', '19.492']
3 : ['10.128', '9.552', '9.277', '9.117', '9.013', '8.941', '8.887', '8.845', '8.812', '8.785', '8.763', '8.745', '8.729', '8.715', '8.703', '8.660', '8.594', '8.572', '8.549', '8.538']
4 : ['7.709', '6.944', '6.591', '6.388', '6.256', '6.163', '6.094', '6.041', '5.999', '5.964', '5.936', '5.912', '5.891', '5.873', '5.858', '5.803', '5.717', '5.688', '5.658', '5.643']
5 : ['6.608', '5.786', '5.409', '5.192', '5.050', '4.950', '4.876', '4.818', '4.772', '4.735', '4.704', '4.678', '4.655', '4.636', '4.619', '4.558', '4.464', '4.431', '4.398', '4.382']
6 : ['5.987', '5.143', '4.757', '4.534', '4.387', '4.2

In [54]:

## A ESTRUTURA DA AMOSTAR DEVE ESTAR NESSE SENTIDO DENTRO DO DICIONARIO = {"TRATAMENTO" : [REPETIÇÃO1, REPETIÇÃO2]}
## onde cada chave representa um tratamento, e o que tiver dentro do array são as repetições
## isso funciona considerando que tem apenas uma variavel sendo observada, talvez dps seja possivel fazer isso onde cada repetição ao inves de ter uma variavel, tenha um array de variaveis
samples: Dict[str,List] = {
                            "A" : [2000, 2300, 2500, 2400],
                            "B" : [1200, 1000, 900, 1050],
                            "C" : [3000, 3400, 3100, 3300],
                            "D" : [700, 600, 900, 600],
                            "E" : [500, 700, 390, 410]
                        }
# samples = sample_data
print(samples)

jorge = np.array([[2000, 2300, 2500, 2400],
                  [1200, 1000, 900, 1050],
                    [3000, 3400, 3100, 3300],
                    [700, 600, 900, 600],
                    [500, 700, 390, 410]])
print(jorge.T)

{'A': [2000, 2300, 2500, 2400], 'B': [1200, 1000, 900, 1050], 'C': [3000, 3400, 3100, 3300], 'D': [700, 600, 900, 600], 'E': [500, 700, 390, 410]}
[[2000 1200 3000  700  500]
 [2300 1000 3400  600  700]
 [2500  900 3100  900  390]
 [2400 1050 3300  600  410]]


In [52]:

k = len(samples.keys())
r = len(list(samples.values())[0])
## GL ## 
# gl_trat = k - 1
gl_trat = k - 1
print(f"GLTrat: {gl_trat.__round__(2)}")
# GLErro = k(r-1) or GLTotal - GLtrat
gl_erro = k * (r - 1)
print(f"GLErro: {gl_erro.__round__(2)}")
# total = k*r-1
gl_total = k * r -1
print(f"GLTotal: {gl_total.__round__(2)}")
## SQ ## 
sum_of_all_samples = 0
sqtr = 0
sq_total = 0
for key in samples.keys():
    summatory = 0
    for data in samples[key]:
        summatory += float(data)
        sq_total += pow(float(data), 2)
    sqtr += pow(summatory, 2)
    sum_of_all_samples += summatory
C = pow(sum_of_all_samples, 2) / (k*r)
#Média
mean = sum_of_all_samples / (k*r)
print(sum_of_all_samples)
#SQTR = Somatório(yi**2) / r - C
sqtr = (sqtr / r) - C
print(f"SQtr: {sqtr.__round__(2)}")
#SQTotal = Somatório(Yij**2) - C
sq_total = sq_total - C
print(f"SQt: {sq_total.__round__(2)}")

#sq_erro = sq_total - sqtr
sq_erro = sq_total - sqtr
print(f"SQe: {sq_erro.__round__(2)}")

## QM
# QMtrat = SQTrat / GLTrat
qm_trat = sqtr / gl_trat
print(f"QMtr: {qm_trat.__round__(2)}")
# QMErro = SQerro / GLerro
qm_erro = sq_erro / gl_erro
print(f"QMe: {qm_erro.__round__(2)}")
fc = qm_trat / qm_erro
print(f"FC: {fc.__round__(2)}")
# CV = sqrt(QMErro) / Media Geral
cv = np.sqrt(qm_erro) / mean
cv = cv * 100
print(f"CV: {cv.__round__(2)}%")

GLTrat: 4
GLErro: 15
GLTotal: 19
30950.0
SQtr: 21490500.0
SQt: 21897575.0
SQe: 407075.0
QMtr: 5372625.0
QMe: 27138.33
FC: 197.97
CV: 10.65%


In [50]:
tabela_dict = {
"Fonte de Váriação" : ["Tratamento", "Erro", "Total", "Média Geral", "CV(%)"],
"GL": [gl_trat.__round__(2), gl_erro.__round__(2), gl_total.__round__(2), "", ""],
"SQ": [sqtr.__round__(2), sq_erro.__round__(2),sq_total.__round__(2),"", ""], 
"QM": [qm_trat.__round__(2),qm_erro.__round__(2),"","", ""], 
"F" : [fc.__round__(2),"","", mean.__round__(2),cv.__round__(2)]}
tabela_dataframe = pd.DataFrame(data=tabela_dict)
# print()
display(Markdown(tabela_dataframe.to_markdown(index=False)))

| Fonte de Váriação   | GL   | SQ         | QM        | F      |
|:--------------------|:-----|:-----------|:----------|:-------|
| Tratamento          | 4    | 21490500.0 | 5372625.0 | 197.97 |
| Erro                | 15   | 407075.0   | 27138.33  |        |
| Total               | 19   | 21897575.0 |           |        |
| Média Geral         |      |            |           | 1547.5 |
| CV(%)               |      |            |           | 10.65  |